from chat_pdf.modules.qdrant_manager import QdrantManager
from chat_pdf.modules.pdf_data_model import PDFData


def demo_query():
    # Assume we already have some stored PDF data
    pdf_data = PDFData(
        text_vectors=[0.1, 0.5, 0.3],  // INPUT_REQUIRED {Replace with actual vectors generated by your vectorizer}
        name="Sample PDF",
        path="/path/to/sample.pdf"
    )
    
    # Initialize Qdrant service manager
    qdrant_manager = QdrantManager()
    
    # Store the PDF data
    qdrant_manager.store_pdf_data(pdf_data)
    
    # Perform a demo query
    query_text = "Sample search string"
    search_results = qdrant_manager.search_pdf_data(query=query_text)
    print(search_results)

if __name__ == "__main__":
    demo_query()
